# Generated by Django 4.0 on 2022-02-12 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'verbose_name': 'notes ', 'verbose_name_plural': 'Notes'},
        ),
    ]
